name: mega_store_task
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Responsive
  flutter_screenutil:
  device_preview:
#Animation
  animated_splash_screen:
  flutter_spinkit:
  flutter_svg:
  badges:
  smooth_page_indicator:
#State Mangement
  bloc:
  flutter_bloc:
  equatable:
#Text Field
  pin_code_fields:
#Rating_Bar
  flutter_rating_bar:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf





